add devise
leloufadel/my_blog_app pull request #9
Opened 2023-10-11 17:12 UTC by leloufadel

Description:
This pull request addresses the project requirements by implementing Devise for user authentication in the blog app. The changes include:

Removal of the current_user method from the ApplicationController as Devise will provide this functionality.
Installation and setup of Devise to handle user registration, login, email confirmation, and password reset.
Modification of Devise views for registration.

![Capture-Do-solo-Project](https://github.com/leloufadel/my_blog_app/assets/122641237/02b8b1e3-470f-4f75-a6db-5ba043c2aaea)

2023-10-11 20:06 UTC, Owusu-Desmond requested changes
Hi @leloufadel , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 20:06 UTC, Owusu-Desmond commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Kindly ensure that you enabled `:confirmable` in the user model which should allow a sure to confirm the registration process below proceeding. You should see something similar to what is below: :point_down: 
  
  ```ruby
	  devise :database_authenticatable, :registerable,
				  :recoverable, :rememberable, :validatable, :confirmable
  ```

2023-10-11 20:06 UTC, Owusu-Desmond commented on app/views/devise/sessions/new.html.erb
> +  <div class="actions">
- [ ] From the project requirement, you should modify the views in device for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A). So make sure that your login page match the wireframe. :pray: 

### Your login page
  ![image](https://github.com/leloufadel/my_blog_app/assets/92303891/e4a50a3f-6919-4701-ae2e-9c4a75fc7c64)


### Wireframe

  ![image](https://github.com/leloufadel/my_blog_app/assets/92303891/31db45fd-2923-4520-a507-72ce9a75487d)

2023-10-12 12:20 UTC, joel-kalema approved these changes
Hi @leloufadel 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights

The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 12:35 UTC, merged